type: array
items:
  type: object
  properties:
    name:
      type: string
      description: The name of the product.
    tName:
      $ref: "./common_enums.yaml#/definitions/tNameProductEnum"
      description: Technical name or specific product variant name.
      nullable: true
    hName:
      type: string
      description: Hindi name of the product.
      nullable: true
    dispName:
      type: string
      description: Display name of the product.
      nullable: true
    brand:
      description: Display name of the product.
      nullable: true
      enum:
        - Dry Fruits
        - Everest
        - Masale
        - Other
    qtyOptions:
      type: array
      nullable: true
    tMul:
      type: number
      description: A multiplier, could be integer or float.
      nullable: true
    mQty:
      type: integer
      description: Master Quantity.
      nullable: true
    unit:
      type: object
      properties:
        unit:
          type: string
          description: The primary unit of the product.
        crushIndex:
          type: integer
          description: An index related to crushing or processing.
        p2pUnit:
          type: object
          properties:
            unit:
              type: string
              description: Point-to-point unit.
            otherChargesMultiplier:
              type: integer
              description: Multiplier for other charges.
            billQuantityMultiplier:
              type: number
              description: Multiplier for bill quantity, can be integer or float.
          required:
            - unit
            - otherChargesMultiplier
            - billQuantityMultiplier
      required:
        - unit
        - crushIndex
        - p2pUnit
    extItems:
      type: array
      description: A list of external or extended items related to the product.
      items:
        type: object
        properties:
          extItem:
            type: string
            description: The name of the extended item.
          tName:
            description: Technical name of the extended item.
            nullable: true
            $ref: "./common_enums.yaml#/definitions/tNameProductEnum"
          dispName:
            type: string
            description: Display name of the product.    
          qtyOptions:
            type: array
            nullable: true
          extP2pUnit:
            type: object
            properties:
              unit:
                type: string
                description: Point-to-point unit for the extended item.
              otherChargesMultiplier:
                type: integer
                description: Multiplier for other charges for the extended item.
              billQuantityMultiplier:
                type: number
                description: Multiplier for bill quantity for the extended item, can be integer or float.
            required:
              - unit
              - otherChargesMultiplier
              - billQuantityMultiplier
        required:
          - extItem
          - extP2pUnit
      nullable: true
  required:
    - name
    - unit